cluster.name: ids-cluster
node.name: opensearch-node1

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings for single node
discovery.type: single-node

# Security settings - disable for development
plugins.security.disabled: true

# Performance settings
bootstrap.memory_lock: false

# Compatibility settings
compatibility.override_main_response_version: true
