cluster.name: ids-cluster
node.name: opensearch-node1

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300

# Discovery settings for single node
discovery.type: single-node

# Security settings - disable for development
plugins.security.disabled: true
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enabled: false

# Performance settings
bootstrap.memory_lock: false
indices.query.bool.max_clause_count: 1024

# Logging
path.logs: /usr/share/opensearch/logs

# Data path
path.data: /usr/share/opensearch/data

# Compatibility settings
compatibility.override_main_response_version: true
